### ISSUE TITLE
Can you please add a screenshot to the readme?

### ISSUE THREAD

**Issue by icyflame** [dfcreative/piano-keyboard#1]
- Just so we can see how the DOM element really looks like.
- If you are still working on this, then, that's awesome!

**Comment by dy** [comment]
Hi) I’ve just created that component (a couple of hours ago), you can see a really raw demo here: http://dfcreative.github.io/piano-keyboard/
I’m going to make it fluent and multitouch on iphone, so patience)
Thanks for the interest!

**Comment by icyflame** [comment]
Sure! I can also help with this, so, open issues regarding the features that you are implementing, when you get time! Thanks!

**Comment by dy** [comment]
Great, thanks! I have a small todo.md - these are things worth considering, but basically I'm going to use this component as a part of [audio-lab](https://github.com/dfcreative/audio-lab). If you have some ideas or use-cases for the component, you are welcome to issue/PR them))
